server:
  port: 9998
spring:
  application:
    name: kafkalistener
  cloud:
    stream:
      bindings:
        loginCreationInputChannel:
          destination: logincreation
          contentType: application/json
          group: idegroup
      kafka:
        binder:
          zkNodes: localhost
          defaultZkPort: 2181
          brokers: localhost
          defaultBrokerPort: 9092